[package]
name = "lisp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7"
thiserror = "1.0"
lazy_static = "1.4"
rustyline = "11.0"
unescape = "0.1"
im = "15.1"
string-interner = "0.14"
