[package]
name = "lisp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"
regex = "1.7"
thiserror = "1.0"
lazy_static = "1.4"
unescape = "0.1"
im = "15.1"
string-interner = "0.14"
ordered-float = "3.0"
rustyline = { version = "11.0", optional = true }

[features]
default = ["io-stdlib", "rustyline"]
# Enable functions in the Lisp standard library which require I/O
io-stdlib = []

[[bin]]
name = "lisp-repl"
required-features = ["io-stdlib", "rustyline"]
path = "src/main.rs"
